### ISSUE TITLE
👍Comment: Good use of dummy objects in testing

### ISSUE THREAD

**Issue by sbinlondon** [fac-14/NDJS-API#22]
https://github.com/fac-14/NDJS-API/blob/df236cfbc24fd346a72ea94df533a134282921c7/test.js#L13

We did not do that and got bogged down in trying to test our actual API requests. Good thinking!

**Comment by jennah2121** [comment]
I agree - its great that you managed to get some testing done! Think about moving your dummy object into a separate file just to make the test file less cluttered.
