### ISSUE TITLE
⚠️Issue: you can compare someone to themselves

### ISSUE THREAD

**Issue by sbinlondon** [fac-14/NDJS-API#28]
You can enter the same username for Github in both fields. I think ideally this would be disabled.

**Comment by jennah2121** [comment]
If it isn't then make sure that the employability factor is the same 
<img width="800" alt="screen shot 2018-07-20 at 10 37 02" src="https://user-images.githubusercontent.com/25872585/42995469-e17a16dc-8c08-11e8-919e-97e44975036e.png">

**Comment by developess** [comment]
We think this is ok that you can do this, if the user really wants to. The employability factor is calculated randomly lol, so it will always be different
