### ISSUE TITLE
🚨Lack of righthand header padding when window is made very small

### ISSUE THREAD

**Issue by sbinlondon** [fac-14/NDJS-API#39]
When I drag my Chrome window to make it super small and see the breakpoints, it looks like there is no righthand padding for the headline. Perhaps add this into your smaller screen media query?

**Comment by jennah2121** [comment]
Padding (or some other form of styling) might be nice here to - your design is usable on mobile though so well done

<img width="550" alt="screen shot 2018-07-20 at 10 54 54" src="https://user-images.githubusercontent.com/25872585/42996477-988cd24a-8c0b-11e8-9ac7-4c2106a12d2d.png">

**Comment by developess** [comment]
Sorted this! Thanks :)
